export * from './HomePage';
export * from './Alumnos';
export * from './Cursos';
export * from './Grados';
export * from './Secciones';
export * from './Unidades';
export * from './UsersPage';
export * from './Notas';
export * from './Error_404'
export * from './Boleta'